language: node_js
node_js: 
   - '8'
cache:
  directories:
    - node_modules
before_install:
  - npm install -g hexo-cli
install:
  - npm install
  - npm install hexo-deployer-git --save
script:
  - hexo clean
  - hexo generate
after_script:
  - git config user.name "jianjustin"
  - git config user.email "janine.jian.chen@gmail.com"
  - sed -i "s/access_token/${ACCESS_TOKEN}/g" ./_config.yml
  - hexo deploy