# Hexo Configuration

# Site
title: 计算机学习室
subtitle:
description:
keywords:
author: 
language:
timezone:

# URL
url: https://learningstudio.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md 
default_layout: post
titlecase: false 
external_link: true 
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Extensions
theme: Material-T

# Deployment
deploy:
  type: git
  repo: https://github.com/learningstudio/learningstudio.github.io.git
  branch: master
  message: "Docs updated: {{ now('YYYY-MM-DD HH:mm:ss') }})"
